config/routes.rb
CmsTest::Application.routes.draw do
  resources :workout_tags

  resources :favorites

  resources :users

  resources :ratings

  match "flag" => "workouts#flag"
  
  resources :workouts

    match "users/create_follow/:id/:followed_user(.:format)" => "users#add_followed_user"
    match "users/remove_follow/:id/:followed_user(.:format)" => "users#remove_followed_user"
    
    match "users/leaderboard/:type(.:format)" => "users#leaderboard"
    match "users/find_fb_friends/:friend_list(.:format)" => "users#find_fb_friends_from_list"

  root :to => 'workouts#index'

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  
  has_attached_file :photo, :url => "/system/photos/:id/:basename.:extension", :path => ":rails_root/public/system/photos/:id/:basename.:extension", :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_many :ratings
  belongs_to :user
  has_many :workout_tags
  
  #tags for doing gmaps and reverse geocoding (gmaps4rails and geocoding gems)
  acts_as_gmappable
  
  reverse_geocoded_by :latitude, :longitude do |obj, results|
    if geo = results.first
      # populate your model
      obj.city    = geo.city
      obj.zipcode = geo.postal_code
    end
  end
  
  geocoded_by :address
  after_validation :fetch_address
  
  
  

  def gmaps4rails_address
    "#{self.latitude}, #{self.longitude}"
  end
  
  def update_average_rating
    x = 0
    puts x
    if self.ratings.count != 0
      self.ratings.each do |rating|
        x += rating.value
      end
      self.average_rating = x / self.ratings.count
      self.save
    else
      self.average_rating = 3
      self.save
    end
  end
  


end

app/controllers/workouts_controller.rb
 class UsersController < ApplicationController
#   # GET /users
#   # GET /users.json
   def index
     @users = User.all
 
     respond_to do |format|
       format.html # index.html.erb
       format.json { render :json  => @users }
     end
   end

  def leaderboard
    if params[:type] == "global"
        @users = User.find(:all, :order => "score", :limit => 10)
    end
    #this probably needs some more checking for edge cases
    if params[:type]=="friends"
      if params[:user_id]
        friends = []
        User.where_fb_id(params[:user_id]).followed_users.each do |friend|
          friends << User.find(friend)
        end
        @users=friends.compact.sort {|a,b| b.score <=> a.score}.slice(0,9)
        
      end
    end
    #PLACEHOLDER!!! FIX FIX FIX!
    if params[:type] == "local"
        @users = User.find(:all, :order => "score", :limit => 10)
    end
        
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json  => @users }
    end
  
  
  end

  def find_fb_friends_from_list
    @users = []
    friend_list=params[:friend_list].slice(1,params[:friend_list].length-2).split(",")
    friend_list.each do |friend|
       @users << User.where_fb_id(friend.to_i)
    end
    @users.compact!
    
    respond_to do |format|
      #format.html # new.html.erb
      format.json { render :json  => @users }
    end
  end
  
  # GET /users/1
  # GET /users/1.json
  def show
    #the mobile app sends fb=true (as it does in other situations)
    #explore moving over to fb id as primary key
    if params[:fb]
      @user = User.where(:fb_id => params[:id]).first
    
      result={}
      @user.attributes.each do |k,v|
        #this if statement is to keep some @user attributes out of results...it feels like it shouldn't be needed, since update should overwrite it, but that doesn't seem to be happening...fix this
        if k != "favorite_workouts" && k != "followed_users"
          result.update(k => v)
        end
      end
    
      #pull the full workout/favorites/ratings attributes out of the database
      workouts = Workout.where(:user_id => @user)
      favorites = Favorite.where(:user_id => @user)
      ratings = Rating.where(:user_id => @user)
      #initialize collecting arrays
      favorite_workouts = []
      completed = []
      friends = []
      
      #are these iterations necessary or am i just being stupid?
      favorites.each do |f|
        begin
          favorite_workouts << Workout.find(f.workout_id)
        rescue
        end
      end
      favorite_workouts.compact!
      
      
      ratings.each do |f|
        begin
          completed << Workout.find(f.workout_id)
        rescue
        end
      end
      completed.compact!
      
      #this one i think is necessary, since it is collecting the attributes of the followed_users
      @user.followed_users.each do |f|
        begin
        friends << User.find(f).attributes
        rescue
        end
      end
      result.update(:favorites => favorite_workouts)
      result.update(:workouts => workouts)
      result.update(:completed => completed)
      result.update(:followed_users => friends)
      
    else
      @user = User.find(params[:id])
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => result}
    end
  end
  
  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json  => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    if params[:fb]
      params[:workout][:user_id] = User.where(:fb_id => params[:user_id]).first.id
    end
    
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice  => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action  => "new" }
        format.json { render :json  => @user.errors, :status  => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice  => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action  => "edit" }
        format.json { render :json  => @user.errors, :status  => :unprocessable_entity }
      end
    end
  end
  
  def add_followed_user
    #NOTE: THIS ONLY INTAKES A SINGLE USER...COULD BE FIXED W/O TOO MUCH TROUBLE THOUGH
    #this and its counterpart assume fb_id
    
    @user = User.where_fb_id(params[:id])
    @followed_user = User.where_fb_id(params[:followed_user])
    
    if @user && @followed_user
      @user.followed_users << @followed_user.id
    end
    respond_to do |format|
    
      if @user.save && @followed_user
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action  => "edit" }
        format.json { render :json  => @user.errors, :status  => :unprocessable_entity }
      end
    end
  end

  def remove_followed_user
    #NOTE: THIS ONLY INTAKES A SINGLE USER...COULD BE FIXED W/O TOO MUCH TROUBLE THOUGH
    #this and its counterpart assume fb_id
    
    @user = User.where_fb_id(params[:id])
    @followed_user = User.where_fb_id(params[:followed_user])
    
    if @user && @followed_user
      @user.followed_users.delete @followed_user.id
    end
    respond_to do |format|
    
      if @user.save && @followed_user
        format.html { redirect_to @user, :notice  => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action  => "edit" }
        format.json { render :json  => @user.errors, :status  => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
 end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<b> PHOTO LABEL </b>
<%= @workout.photo_label %>



<%= form_for @workout, :html => { :multipart => true } do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
	<b>photo file goes here </b>
	<%= f.file_field :photo %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sponsored %><br />
    <%= f.check_box :sponsored %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
<div class="field">
    <%= f.label :fitness_tags %><br />
    <%= f.text_field :fitness_tags %>
  </div>
<div class="field">
    <%= f.label :obstacle %><br />
    <%= f.text_field :obstacle %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br />
    <%= f.text_field :difficulty %>
  </div>
 <div class="field">
    <%= f.label :MH_suggests %><br />
    <%= f.text_field :MH_suggests %>
  </div>
<div class="field">
    <%= f.label :editor_comments %><br />
    <%= f.text_field :editor_comments %>
  </div>


  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :flagged %><br />
    <%= f.check_box :flagged %>
  </div>
	    


<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<h1>Listing workouts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
	<th>Difficulty</th>
    <th>City</th>
    <th>Photo Label</th>
	<th>Zip Code</th>
   	<th>Latitude</th>
    <th>Longitude</th>
    <th>Flagged</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @workouts.each do |workout| %>
  <tr>
    <td><%= workout.name %></td>
    <td><%= workout.description %></td>
	<td><%= workout.difficulty %></td>
    <td><%= workout.city %></td>
	<td><%= workout.photo_label %></td>
   	<td><%= workout.zipcode %></td>
	<td><%= workout.latitude %></td>
    <td><%= workout.longitude %></td>
    <td><%= workout.flagged %></td>
    <td><%= link_to 'Show', workout %></td>
    <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
    <td><%= link_to 'Destroy', workout, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Workout', new_workout_path %>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<%= link_to 'Home', workouts_path %>

<%= image_tag @workout.photo.url(:thumb), :height => '50', :width => '50'  %>



<%= gmaps4rails(@json)%>


<p>
  <b>Name:</b>
  <%= @workout.name %>
</p>
<p>
  <b>Sponsored:</b>
  <%= @workout.sponsored %>
</p>
<p>
  <b>Created At:</b>
  <%= @workout.created_at %>
</p>
<p>
	<b>Location:</b>
	<% begin %>
	<%= @workout.city%>
	<% rescue %>
	ok that didn't work
	<% end %>



<p>
  <b>Description:</b>
  <%= @workout.description %>
</p>
  <b>Difficulty:</b>
  <%= @workout.difficulty %>
</p>

<p>
  <b>Latitude:</b>
  <%= @workout.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @workout.longitude %>
</p>


<p>
  <b>Editor Comments:</b>
  <%= @workout.editor_comments %>
</p>

<p>
  <b>Men's Health Suggests:</b>
  <%= @workout.MH_suggests %>
</p>

<p>
  <b>Flagged:</b>
  <%= @workout.flagged %>
</p>
<p>
	<p>
	  <b>User Created by user #:</b>
	  <%= @workout.created_by_id %>
	</p>
	<p>

 <%# @workout.workout_tags.each do |tag| %>
<p> 	
<%#= tag.category + " : " + tag.name  %> 
</p>
	<%# end %>


<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>