config/routes.rb
CmsTest::Application.routes.draw do
  resources :workout_tags

  resources :favorites

  resources :users

  resources :ratings

  match "flag" => "workouts#flag"
  
  resources :workouts

    match "users/create_follow/:id/:followed_user(.:format)" => "users#add_followed_user"
    match "users/remove_follow/:id/:followed_user(.:format)" => "users#remove_followed_user"
    
    match "users/leaderboard/:type(.:format)" => "users#leaderboard"
    match "users/find_fb_friends/:friend_list(.:format)" => "users#find_fb_friends_from_list"

  root :to => 'workouts#index'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :workout
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @favorites }
    end
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @favorite }
    end
  end

  # GET /favorites/new
  # GET /favorites/new.json
  def new
    @favorite = Favorite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @favorite }
    end
  end

  # GET /favorites/1/edit
  def edit
    @favorite = Favorite.find(params[:id])
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(params[:favorite])

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to @favorite, :notice => 'Favorite was successfully created.' }
        format.json { render :json => @favorite, :status => :created, location: @favorite }
      else
        format.html { render :action => "new" }
        format.json { render :json => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /favorites/1
  # PUT /favorites/1.json
  def update
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      if @favorite.update_attributes(params[:favorite])
        format.html { redirect_to @favorite, :notice => 'Favorite was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to favorites_url }
      format.json { head :ok }
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :workout_id %><br />
    <%= f.number_field :workout_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<h1>Listing favorites</h1>

<table>
  <tr>
    <th>User</th>
    <th>Workout</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @favorites.each do |favorite| %>
  <tr>
    <td><%= favorite.user_id %></td>
    <td><%= favorite.workout_id %></td>
    <td><%= link_to 'Show', favorite %></td>
    <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
    <td><%= link_to 'Destroy', favorite, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @favorite.user_id %>
</p>

<p>
  <b>Workout:</b>
  <%= @favorite.workout_id %>
</p>


<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>